# setup.R
rm(list=ls())
knitr::opts_chunk$set(echo = TRUE)

library(RPostgreSQL)
library(dplyr)
library(dbplyr)
library(data.table)
library(lubridate)
library(reshape2)
library(stringr)
library(tidyverse)
library(readxl)
library(knitr)
library(ggplot2)
library(arules)
library(arulesViz)
library(randomForest)
library(kernlab)
library(e1071)
library(nnet)
library(neuralnet)
library(fastDummies)
library(class)
